services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
      image: vladislav1234512345/topten:1.0.1
      command: >
        sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db


volumes:
  postgres_data: