services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ${ROOT_PATH}/env_files/.env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"

  rabbitmq-managment:
    image: rabbitmq:4.0-management
    restart: always
    ports:
      - "15672:15672"

  backend:
      image: ${IMAGE_NAME}
      restart: always
      command: >
        sh -c "celery -A src.worker worker --loglevel=INFO --pool=solo & python3 src/main.py"
      volumes:
        - ${ROOT_PATH}/env_files:/usr/src/app/env_files
        - ${ROOT_PATH}/certs:/usr/src/app/certs
      env_file:
        - ${ROOT_PATH}/env_files/.env
        - ${ROOT_PATH}/env_files/.env.db
        - ${ROOT_PATH}/env_files/.env.email
        - ${ROOT_PATH}/env_files/.env.tasks
      ports:
        - "8000:8000"
      depends_on:
        - db
        - redis

volumes:
  postgres_data:
