services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ${PWD}/env_files/.env.db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  rabbitmq-managment:
    image: rabbitmq:4.0-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - ${RABBITMQ_MANAGMENT_PORT}:${RABBITMQ_MANAGMENT_PORT}

  backend:
      image: ${IMAGE_NAME}
      restart: always
      command: >
        sh -c "celery -A src.worker worker --loglevel=INFO --pool=solo & python3 src/main.py"
      volumes:
        - ${PWD}/env_files:/usr/src/app/env_files
        - ${PWD}/certs:/usr/src/app/certs
      env_file:
        - ${PWD}/env_files/.env
        - ${PWD}/env_files/.env.cookies
        - ${PWD}/env_files/.env.db
        - ${PWD}/env_files/.env.email
        - ${PWD}/env_files/.env.tasks
      ports:
        - ${BACKEND_PORT}:${BACKEND_PORT}
      depends_on:
        - db
        - redis

volumes:
  postgres_data:
